global:
  max:
    ue: 1024

upf:
  pfcp:
    server:
      - address: 192.168.200.100
    client:

  gtpu:
    server:
      - address: 192.168.200.100

  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: "internet"

  metrics:
    server:
      - address: 192.168.200.100
        port: 9090