global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.

smf:
  sbi:
    server:
      - address: 192.168.200.70
        port: 7777
    client:
      nrf:
        - uri: http://192.168.200.50:7777

  pfcp:
    server:
      - address: 192.168.200.70
    client:
      upf:
        - address: 192.168.200.100

  gtpc:
    server:
      - address: 192.168.200.70

  gtpu:
    server:
      - address: 192.168.200.70

  metrics:
    server:
      - address: 192.168.200.70
        port: 9090

  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1

  dns:
    - 8.8.8.8
    - 8.8.4.4